// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnCcjkzcw7a8-GNomsMOQsSffC6AT0O0A',
    appId: '1:918433060624:web:2a754796bf6e123b57f795',
    messagingSenderId: '918433060624',
    projectId: 'fir-storage-333c6',
    authDomain: 'fir-storage-333c6.firebaseapp.com',
    storageBucket: 'fir-storage-333c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkuu9lgaWX-nXYE5S5IkSJypXDghFrGQ8',
    appId: '1:918433060624:android:63b07ebb584aeca357f795',
    messagingSenderId: '918433060624',
    projectId: 'fir-storage-333c6',
    storageBucket: 'fir-storage-333c6.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnCcjkzcw7a8-GNomsMOQsSffC6AT0O0A',
    appId: '1:918433060624:web:8790683ac487960b57f795',
    messagingSenderId: '918433060624',
    projectId: 'fir-storage-333c6',
    authDomain: 'fir-storage-333c6.firebaseapp.com',
    storageBucket: 'fir-storage-333c6.appspot.com',
  );
}
